export interface Product {
  id: string
  name: string
  price: number
  category: "outerwear" | "tops" | "bottoms"
  colors: string[]
  sizes: string[]
  images: string[]
  description: string
  details: string
  materials: string
}

export const products: Product[] = [
  {
    id: "1",
    name: "Oversized Wool Coat",
    price: 1890,
    category: "outerwear",
    colors: ["Black & White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764726767/coat_main_qhsbaf.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764726766/coat_back_fa2slp.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764726767/coat_detail_tq5j4n.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764726768/coat_flat_l9benm.png",
    ],
    description: "A timeless oversized silhouette in premium Italian wool. The half-black half-white design embodies the SEESAW philosophy of balance in duality.",
    details: "Dropped shoulders, concealed button closure, side pockets, fully lined. Dry clean only.",
    materials: "100% Virgin Wool. Lining: 100% Cupro.",
  },
  {
    id: "2",
    name: "Structured Blazer",
    price: 1450,
    category: "outerwear",
    colors: ["Black & White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764724667/blazer-main_boiie3.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764724666/blazer-back_ehnpta.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764724667/blazer-detail_zfmyy5.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764724666/blazer-flat_g8xi35.png",
    ],
    description: "Sharp lines and impeccable tailoring define this essential half-black half-white blazer. A statement piece that embodies the SEESAW philosophy of balance in duality.",
    details: "Peak lapels, single-breasted, single-button closure, interior pockets. Dry clean only.",
    materials: "98% Wool, 2% Elastane. Lining: 100% Viscose.",
  },
  {
    id: "3",
    name: "Minimal Trench",
    price: 1650,
    category: "outerwear",
    colors: ["Beige & Black"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764727907/trench_main_amz1nz.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764727908/trench_back_fkrsbx.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764728342/trench_detail_clmjqg.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764727906/trench_flat_zxyh2z.png",
    ],
    description: "A reimagined classic with clean lines and modern proportions. The half-beige half-black design brings a fresh perspective to the timeless trench.",
    details: "Belt with tonal buckle, storm flap, slash pockets. Water-resistant. Dry clean only.",
    materials: "100% Cotton with water-resistant coating. Lining: 100% Cotton.",
  },
  {
    id: "4",
    name: "Cashmere Cardigan",
    price: 980,
    category: "tops",
    colors: ["Cream & Camel"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764730675/cardigan_main_jh5wdb.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764730673/cardigan_back_dvo7bs.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764730673/cardigan_detail_hgqtor.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764730672/cardigan_flat_aqxs3f.png",
    ],
    description: "Luxuriously soft cashmere in a relaxed silhouette. The half-cream half-camel design brings warmth and sophistication to this essential piece.",
    details: "V-neck, button-front closure, ribbed cuffs and hem. Hand wash or dry clean.",
    materials: "100% Mongolian Cashmere.",
  },
  {
    id: "5",
    name: "Silk Blouse",
    price: 680,
    category: "tops",
    colors: ["Black & Ivory"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764739616/blouse_main_x033uo.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764739613/blouse_back_hjzkzm.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764739615/blouse_detail_b896ak.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764739615/blouse_flat_lbwrd0.png",
    ],
    description: "Fluid silk with a subtle sheen. The half-black half-ivory design creates a striking contrast that embodies effortless elegance.",
    details: "Point collar, concealed button placket, French cuffs. Dry clean only.",
    materials: "100% Mulberry Silk.",
  },
  {
    id: "6",
    name: "Cotton Poplin Shirt",
    price: 420,
    category: "tops",
    colors: ["Black & White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764740167/shirt_main_ijcizr.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764740166/shirt_back_adp9qf.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764740168/shirt_detail_ke7s4f.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764740165/shirt_flat_djbcdp.png",
    ],
    description: "Crisp cotton with a subtle, architectural drape. The half-black half-white design adds a bold statement to this classic silhouette.",
    details: "Spread collar, mother-of-pearl buttons, barrel cuffs. Machine wash cold.",
    materials: "100% Egyptian Cotton.",
  },
  {
    id: "7",
    name: "Merino Turtleneck",
    price: 380,
    category: "tops",
    colors: ["Black & Charcoal"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764741152/Turtleneck_main_cfxscd.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764741148/Turtleneck_back_clw6hc.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764741150/Turtleneck_detail_sn3lab.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764741150/Turtleneck_flat_f44dqi.png",
    ],
    description: "Fine-gauge merino wool with a refined, slim fit. The half-black half-charcoal design creates subtle contrast within a tonal palette.",
    details: "Foldover turtleneck, ribbed cuffs and hem. Hand wash or dry clean.",
    materials: "100% Extra-Fine Merino Wool.",
  },
  {
    id: "8",
    name: "Wide Leg Trousers",
    price: 620,
    category: "bottoms",
    colors: ["Black & Beige"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764742009/Leg_Trousers_main_vy67nj.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764742008/Leg_Trousers_back_ntniq9.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764742011/Leg_Trousers_detail_yheoic.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764742007/Leg_Trousers_flat_pbhq2u.png",
    ],
    description: "Fluid, wide-leg silhouette with a high waist. One leg black, one leg beige for a bold statement of duality.",
    details: "High-rise, pleated front, side pockets, zip fly. Dry clean only.",
    materials: "100% Wool Crepe.",
  },
  {
    id: "9",
    name: "Tailored Slim Trousers",
    price: 580,
    category: "bottoms",
    colors: ["Black & Cream"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764743511/Slim_Trousers_main_inpfuo.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764743513/Slim_Trousers_back_ejtn3z.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764743515/Slim_Trousers_detail_tdvld3.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764743510/Slim_Trousers_flat_lavrtf.png",
    ],
    description: "Impeccably tailored with a slim, modern silhouette. One leg black, one leg cream for a bold runway statement.",
    details: "Mid-rise, flat front, slash pockets, hook-and-bar closure. Dry clean only.",
    materials: "98% Wool, 2% Elastane.",
  },
  {
    id: "10",
    name: "Pleated Midi Skirt",
    price: 520,
    category: "bottoms",
    colors: ["Black & Ivory"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764744434/Midi_Skirt_main_ep8ry2.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764744428/Midi_Skirt_back_ntyarm.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764744429/Midi_Skirt_detail_wtlmym.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764744431/Midi_Skirt_flat_kxsgha.png",
    ],
    description: "Elegant pleats with graceful movement. Half black, half ivory for a striking contrast.",
    details: "High-waisted, concealed side zip, fully lined. Dry clean only.",
    materials: "100% Polyester Crepe. Lining: 100% Polyester.",
  },
  {
    id: "11",
    name: "Minimal Bomber Jacket",
    price: 890,
    category: "outerwear",
    colors: ["Black & Silver"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764745097/Bomber_Jacket_main_kkukzs.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764745099/Bomber_Jacket_back_y7rhai.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764745102/Bomber_Jacket_detail_w6bnzr.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764745096/Bomber_Jacket_flat_n4x7kn.png",
    ],
    description: "Clean lines redefine the classic bomber. Half black, half silver for a modern edge.",
    details: "Zip closure, ribbed collar and cuffs, side pockets. Dry clean only.",
    materials: "100% Nylon. Lining: 100% Polyester.",
  },
  {
    id: "12",
    name: "Oversized Knit Sweater",
    price: 540,
    category: "tops",
    colors: ["Cream & Black"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764745848/Knit_Sweater_main_rodnzn.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764745841/Knit_Sweater_back_lnratp.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764745842/Knit_Sweater_detail_sile1e.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764745845/Knit_Sweater_flat_fyarsz.png",
    ],
    description: "Chunky knit in a relaxed, oversized silhouette. Half cream, half black for cozy contrast.",
    details: "Crew neck, dropped shoulders, ribbed trim. Hand wash cold.",
    materials: "70% Wool, 30% Alpaca.",
  },
  {
    id: "13",
    name: "Asymmetric Top",
    price: 420,
    category: "tops",
    colors: ["Black & White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764746552/Asymmetric_Top_main_uetufx.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764746558/Asymmetric_Top_back_z9mwc7.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764746555/Asymmetric_Top_detail_peea8e.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764746551/Asymmetric_Top_flat_b8efae.png",
    ],
    description: "Architectural asymmetry meets fluid drape. Half black, half white for bold contrast.",
    details: "Asymmetric hem, one-shoulder option, side slit. Machine wash cold.",
    materials: "95% Viscose, 5% Elastane.",
  },
  {
    id: "14",
    name: "Cropped Jacket",
    price: 780,
    category: "outerwear",
    colors: ["Black & Beige"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764813915/Cropped_Jacket_main_otoqpu.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764813914/Cropped_Jacket_back_xxgnzm.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764813914/Cropped_Jacket_detail_hgdi7q.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764813915/Cropped_Jacket_flat_pd7rnj.png",
    ],
    description: "Cropped proportions with structured shoulders. Half black, half beige split design.",
    details: "Notch lapels, single button closure, cropped length. Dry clean only.",
    materials: "100% Wool. Lining: 100% Cupro.",
  },
  {
    id: "15",
    name: "Drawstring Trousers",
    price: 480,
    category: "bottoms",
    colors: ["Black & Beige"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764814619/Drawstring_Trousers_main_gce4fa.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764814617/Drawstring_Trousers_back_p4gdfj.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764814618/Drawstring_Trousers_detail_i91ean.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764814617/Drawstring_Trousers_flat_kbv2el.png",
    ],
    description: "Relaxed elegance with an elasticated waist. Half black, half beige split design.",
    details: "High-rise, drawstring waist, tapered leg, side pockets. Machine wash cold.",
    materials: "100% Cotton Twill.",
  },
  {
    id: "16",
    name: "Wool Vest",
    price: 620,
    category: "tops",
    colors: ["Black & Beige"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764815162/Wool_Vest_main_uphse9.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764815163/Wool_Vest_back_l1wkcm.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764815210/Wool_Vest_detail_lofovo.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764815161/Wool_Vest_flat_qwukom.png",
    ],
    description: "Sleek layering piece with refined tailoring. Half black, half beige split design.",
    details: "V-neck, button front, welt pockets, fully lined. Dry clean only.",
    materials: "100% Wool. Lining: 100% Viscose.",
  },
  {
    id: "17",
    name: "Long Sleeve Dress",
    price: 890,
    category: "tops",
    colors: ["Black & White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764817907/Long_Sleeve_Dress_main_zigp9k.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764817906/Long_Sleeve_Dress_back_zkewvm.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764817906/Long_Sleeve_Dress_detail_refapp.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764817905/Long_Sleeve_Dress_flat_apq6pc.png",
    ],
    description: "Understated elegance in a fluid midi silhouette. Half black, half white split design.",
    details: "Crew neck, concealed back zip, midi length. Dry clean only.",
    materials: "100% Viscose Crepe.",
  },
  {
    id: "18",
    name: "Leather Belt",
    price: 280,
    category: "bottoms",
    colors: ["Black", "Beige"],
    sizes: ["S", "M", "L"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Minimal hardware meets premium leather.",
    details: "Italian leather, tonal buckle, 3cm width.",
    materials: "100% Italian Calf Leather.",
  },
  {
    id: "19",
    name: "Double-Breasted Coat",
    price: 2200,
    category: "outerwear",
    colors: ["Black", "Navy", "Beige"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Timeless double-breasted silhouette in luxurious wool.",
    details: "Peak lapels, six-button closure, side pockets, back vent. Dry clean only.",
    materials: "100% Cashmere Wool. Lining: 100% Cupro.",
  },
  {
    id: "20",
    name: "Ribbed Tank Top",
    price: 180,
    category: "tops",
    colors: ["Black & White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764820943/Tank_Top_main_gzcs56.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764820885/Tank_Top_back_n5zayc.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764820945/Tank_Top_detail_fmhps0.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764820910/Tank_Top_flat_urbczt.png",
    ],
    description: "Essential ribbed knit with a refined fit. Half black, half white split design.",
    details: "Slim fit, scoop neck, ribbed construction. Machine wash cold.",
    materials: "95% Cotton, 5% Elastane.",
  },
  {
    id: "21",
    name: "Wrap Skirt",
    price: 480,
    category: "bottoms",
    colors: ["Black & Beige"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764821631/Wrap_Skirt_main_p8a0v2.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764821629/Wrap_Skirt_back_evvu4v.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764821633/Wrap_Skirt_detail_atu8xs.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764821630/Wrap_Skirt_flat_oethnn.png",
    ],
    description: "Elegant wrap silhouette with adjustable fit. Half black, half beige split design.",
    details: "High-waisted, self-tie closure, midi length. Dry clean only.",
    materials: "100% Wool Crepe.",
  },
  {
    id: "22",
    name: "Utility Jacket",
    price: 720,
    category: "outerwear",
    colors: ["Ivory & Black"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764822535/Utility_Jacket_main_fehpjq.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764822534/Utility_Jacket_back_pnbbr8.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764822554/Utility_Jacket_detail_dtmsnb.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764822533/Utility_Jacket_flat_zxicmr.png",
    ],
    description: "Functional details meet minimal design. Half ivory, half black split design.",
    details: "Zip closure, patch pockets, adjustable drawstring hem. Machine wash cold.",
    materials: "100% Cotton Canvas.",
  },
  {
    id: "23",
    name: "Silk Camisole",
    price: 320,
    category: "tops",
    colors: ["Champagne & Black"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764823152/Silk_Camisole_main_n7fbr3.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764823154/Silk_Camisole_back_yikts9.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764823152/Silk_Camisole_detail_geanlf.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764823150/Silk_Camisole_flat_jghnnt.png",
    ],
    description: "Delicate silk with refined spaghetti straps. Half champagne, half black split design.",
    details: "Adjustable straps, V-neck, relaxed fit. Dry clean only.",
    materials: "100% Mulberry Silk.",
  },
  {
    id: "24",
    name: "High-Waist Shorts",
    price: 380,
    category: "bottoms",
    colors: ["Navy & Cream"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764828269/High-Waist_Shorts_main_elrpwa.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764828268/High-Waist_Shorts_back_cxfo4e.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764828272/High-Waist_Shorts_detail_ie8vih.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764828267/High-Waist_Shorts_flat_fqberb.png",
    ],
    description: "Tailored shorts with a refined, high-waisted silhouette. Half navy, half cream split design.",
    details: "High-rise, pleated front, side pockets, concealed zip. Dry clean only.",
    materials: "100% Wool Gabardine.",
  },
  {
    id: "25",
    name: "Collarless Coat",
    price: 1750,
    category: "outerwear",
    colors: ["Camel & Ivory"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764829175/Collarless_Coat_main_e1zyoj.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764829174/Collarless_Coat_back_af6hly.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764829178/Collarless_Coat_detail_dvj90q.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764829172/Collarless_Coat_flat_jo6rnq.png",
    ],
    description: "Clean, collarless design with a modern edge. Half camel, half ivory split design.",
    details: "Concealed snap closure, patch pockets, fully lined. Dry clean only.",
    materials: "90% Wool, 10% Cashmere. Lining: 100% Viscose.",
  },
  {
    id: "26",
    name: "Relaxed Blazer",
    price: 980,
    category: "outerwear",
    colors: ["Black", "Beige", "Navy"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Unstructured blazer with an effortless silhouette.",
    details: "Notch lapels, two-button closure, patch pockets, unlined. Dry clean only.",
    materials: "100% Linen.",
  },
]

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "all") return products
  return products.filter((p) => p.category === category)
}

export function getFeaturedProducts(): Product[] {
  return products.slice(0, 4)
}
