export interface Product {
  id: string
  name: string
  price: number
  category: "outerwear" | "tops" | "bottoms"
  colors: string[]
  sizes: string[]
  images: string[]
  description: string
  details: string
  materials: string
}

export const products: Product[] = [
  {
    id: "1",
    name: "Oversized Wool Coat",
    price: 1890,
    category: "outerwear",
    colors: ["Black & White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764726767/coat_main_qhsbaf.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764726766/coat_back_fa2slp.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764726767/coat_detail_tq5j4n.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764726768/coat_flat_l9benm.png",
    ],
    description: "A timeless oversized silhouette in premium Italian wool. The half-black half-white design embodies the SEESAW philosophy of balance in duality.",
    details: "Dropped shoulders, concealed button closure, side pockets, fully lined. Dry clean only.",
    materials: "100% Virgin Wool. Lining: 100% Cupro.",
  },
  {
    id: "2",
    name: "Structured Blazer",
    price: 1450,
    category: "outerwear",
    colors: ["Black & White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764724667/blazer-main_boiie3.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764724666/blazer-back_ehnpta.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764724667/blazer-detail_zfmyy5.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764724666/blazer-flat_g8xi35.png",
    ],
    description: "Sharp lines and impeccable tailoring define this essential half-black half-white blazer. A statement piece that embodies the SEESAW philosophy of balance in duality.",
    details: "Peak lapels, single-breasted, single-button closure, interior pockets. Dry clean only.",
    materials: "98% Wool, 2% Elastane. Lining: 100% Viscose.",
  },
  {
    id: "3",
    name: "Minimal Trench",
    price: 1650,
    category: "outerwear",
    colors: ["Beige & Black"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764727907/trench_main_amz1nz.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764727908/trench_back_fkrsbx.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764728342/trench_detail_clmjqg.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764727906/trench_flat_zxyh2z.png",
    ],
    description: "A reimagined classic with clean lines and modern proportions. The half-beige half-black design brings a fresh perspective to the timeless trench.",
    details: "Belt with tonal buckle, storm flap, slash pockets. Water-resistant. Dry clean only.",
    materials: "100% Cotton with water-resistant coating. Lining: 100% Cotton.",
  },
  {
    id: "4",
    name: "Cashmere Cardigan",
    price: 980,
    category: "tops",
    colors: ["Cream & Camel"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764730675/cardigan_main_jh5wdb.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764730673/cardigan_back_dvo7bs.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764730673/cardigan_detail_hgqtor.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764730672/cardigan_flat_aqxs3f.png",
    ],
    description: "Luxuriously soft cashmere in a relaxed silhouette. The half-cream half-camel design brings warmth and sophistication to this essential piece.",
    details: "V-neck, button-front closure, ribbed cuffs and hem. Hand wash or dry clean.",
    materials: "100% Mongolian Cashmere.",
  },
  {
    id: "5",
    name: "Silk Blouse",
    price: 680,
    category: "tops",
    colors: ["Black & Ivory"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764739616/blouse_main_x033uo.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764739613/blouse_back_hjzkzm.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764739615/blouse_detail_b896ak.png",
      "https://res.cloudinary.com/dz1ldzzf3/image/upload/v1764739615/blouse_flat_lbwrd0.png",
    ],
    description: "Fluid silk with a subtle sheen. The half-black half-ivory design creates a striking contrast that embodies effortless elegance.",
    details: "Point collar, concealed button placket, French cuffs. Dry clean only.",
    materials: "100% Mulberry Silk.",
  },
  {
    id: "6",
    name: "Cotton Poplin Shirt",
    price: 420,
    category: "tops",
    colors: ["White", "Black"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Crisp cotton with a subtle, architectural drape.",
    details: "Spread collar, mother-of-pearl buttons, barrel cuffs. Machine wash cold.",
    materials: "100% Egyptian Cotton.",
  },
  {
    id: "7",
    name: "Merino Turtleneck",
    price: 380,
    category: "tops",
    colors: ["Black", "White", "Navy"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Fine-gauge merino wool with a refined, slim fit.",
    details: "Foldover turtleneck, ribbed cuffs and hem. Hand wash or dry clean.",
    materials: "100% Extra-Fine Merino Wool.",
  },
  {
    id: "8",
    name: "Wide Leg Trousers",
    price: 620,
    category: "bottoms",
    colors: ["Black", "Beige", "Navy"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Fluid, wide-leg silhouette with a high waist.",
    details: "High-rise, pleated front, side pockets, zip fly. Dry clean only.",
    materials: "100% Wool Crepe.",
  },
  {
    id: "9",
    name: "Tailored Slim Trousers",
    price: 580,
    category: "bottoms",
    colors: ["Black", "Navy"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Impeccably tailored with a slim, modern silhouette.",
    details: "Mid-rise, flat front, slash pockets, hook-and-bar closure. Dry clean only.",
    materials: "98% Wool, 2% Elastane.",
  },
  {
    id: "10",
    name: "Pleated Midi Skirt",
    price: 520,
    category: "bottoms",
    colors: ["Black", "Beige"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Elegant pleats with graceful movement.",
    details: "High-waisted, concealed side zip, fully lined. Dry clean only.",
    materials: "100% Polyester Crepe. Lining: 100% Polyester.",
  },
  {
    id: "11",
    name: "Minimal Bomber Jacket",
    price: 890,
    category: "outerwear",
    colors: ["Black", "Navy"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Clean lines redefine the classic bomber.",
    details: "Zip closure, ribbed collar and cuffs, side pockets. Dry clean only.",
    materials: "100% Nylon. Lining: 100% Polyester.",
  },
  {
    id: "12",
    name: "Oversized Knit Sweater",
    price: 540,
    category: "tops",
    colors: ["White", "Black", "Beige"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Chunky knit in a relaxed, oversized silhouette.",
    details: "Crew neck, dropped shoulders, ribbed trim. Hand wash cold.",
    materials: "70% Wool, 30% Alpaca.",
  },
  {
    id: "13",
    name: "Asymmetric Top",
    price: 420,
    category: "tops",
    colors: ["Black", "White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Architectural asymmetry meets fluid drape.",
    details: "Asymmetric hem, one-shoulder option, side slit. Machine wash cold.",
    materials: "95% Viscose, 5% Elastane.",
  },
  {
    id: "14",
    name: "Cropped Jacket",
    price: 780,
    category: "outerwear",
    colors: ["Black", "Beige"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Cropped proportions with structured shoulders.",
    details: "Notch lapels, single button closure, cropped length. Dry clean only.",
    materials: "100% Wool. Lining: 100% Cupro.",
  },
  {
    id: "15",
    name: "Drawstring Trousers",
    price: 480,
    category: "bottoms",
    colors: ["Black", "Beige", "Navy"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Relaxed elegance with an elasticated waist.",
    details: "High-rise, drawstring waist, tapered leg, side pockets. Machine wash cold.",
    materials: "100% Cotton Twill.",
  },
  {
    id: "16",
    name: "Wool Vest",
    price: 620,
    category: "tops",
    colors: ["Black", "Beige"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Sleek layering piece with refined tailoring.",
    details: "V-neck, button front, welt pockets, fully lined. Dry clean only.",
    materials: "100% Wool. Lining: 100% Viscose.",
  },
  {
    id: "17",
    name: "Long Sleeve Dress",
    price: 890,
    category: "tops",
    colors: ["Black", "Navy"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Understated elegance in a fluid midi silhouette.",
    details: "Crew neck, concealed back zip, midi length. Dry clean only.",
    materials: "100% Viscose Crepe.",
  },
  {
    id: "18",
    name: "Leather Belt",
    price: 280,
    category: "bottoms",
    colors: ["Black", "Beige"],
    sizes: ["S", "M", "L"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Minimal hardware meets premium leather.",
    details: "Italian leather, tonal buckle, 3cm width.",
    materials: "100% Italian Calf Leather.",
  },
  {
    id: "19",
    name: "Double-Breasted Coat",
    price: 2200,
    category: "outerwear",
    colors: ["Black", "Navy", "Beige"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Timeless double-breasted silhouette in luxurious wool.",
    details: "Peak lapels, six-button closure, side pockets, back vent. Dry clean only.",
    materials: "100% Cashmere Wool. Lining: 100% Cupro.",
  },
  {
    id: "20",
    name: "Ribbed Tank Top",
    price: 180,
    category: "tops",
    colors: ["White", "Black"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Essential ribbed knit with a refined fit.",
    details: "Slim fit, scoop neck, ribbed construction. Machine wash cold.",
    materials: "95% Cotton, 5% Elastane.",
  },
  {
    id: "21",
    name: "Wrap Skirt",
    price: 480,
    category: "bottoms",
    colors: ["Black", "Beige"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Elegant wrap silhouette with adjustable fit.",
    details: "High-waisted, self-tie closure, midi length. Dry clean only.",
    materials: "100% Wool Crepe.",
  },
  {
    id: "22",
    name: "Utility Jacket",
    price: 720,
    category: "outerwear",
    colors: ["Black", "Beige"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Functional details meet minimal design.",
    details: "Zip closure, patch pockets, adjustable drawstring hem. Machine wash cold.",
    materials: "100% Cotton Canvas.",
  },
  {
    id: "23",
    name: "Silk Camisole",
    price: 320,
    category: "tops",
    colors: ["White", "Black"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Delicate silk with refined spaghetti straps.",
    details: "Adjustable straps, V-neck, relaxed fit. Dry clean only.",
    materials: "100% Mulberry Silk.",
  },
  {
    id: "24",
    name: "High-Waist Shorts",
    price: 380,
    category: "bottoms",
    colors: ["Black", "Beige"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Tailored shorts with a refined, high-waisted silhouette.",
    details: "High-rise, pleated front, side pockets, concealed zip. Dry clean only.",
    materials: "100% Wool Gabardine.",
  },
  {
    id: "25",
    name: "Collarless Coat",
    price: 1750,
    category: "outerwear",
    colors: ["Black", "Beige"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Clean, collarless design with a modern edge.",
    details: "Concealed snap closure, patch pockets, fully lined. Dry clean only.",
    materials: "90% Wool, 10% Cashmere. Lining: 100% Viscose.",
  },
  {
    id: "26",
    name: "Relaxed Blazer",
    price: 980,
    category: "outerwear",
    colors: ["Black", "Beige", "Navy"],
    sizes: ["XS", "S", "M", "L", "XL"],
    images: [
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
      "/placeholder.svg?height=800&width=600",
    ],
    description: "Unstructured blazer with an effortless silhouette.",
    details: "Notch lapels, two-button closure, patch pockets, unlined. Dry clean only.",
    materials: "100% Linen.",
  },
]

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "all") return products
  return products.filter((p) => p.category === category)
}

export function getFeaturedProducts(): Product[] {
  return products.slice(0, 4)
}
